export { WorkbenchShell } from "./components/workbench-shell";
export { WorkspacePanel } from "./components/workspace-panel";
export { PanelResizeHandle } from "./components/panel-resize-handle";
export { ActivityRail } from "./components/activity-rail";
export { WorkbenchStateHydrator } from "./components/workbench-state-hydrator";
export { workbenchActivityItems, workbenchUtilityItems } from "./config/workbench-activity";
export { DEFAULT_WORKBENCH_LAYOUT, WORKBENCH_PANEL_LIMITS, useWorkbenchStore } from "./store/workbench-store";
export type { WorkbenchPanelId, WorkbenchShellLabels, WorkbenchShellProps, WorkbenchShellStyle } from "./model/workbench.types";
export type { PanelCollapseDirection, PanelResizeHandleProps, WorkspacePanelProps } from "./model/panel.types";
export type { ActivityRailItem, ActivityRailProps } from "./model/activity-rail.types";
export type { PanelSizeLimits, PersistedWorkbenchLayout, WorkbenchLayoutState, WorkbenchStore } from "./model/workbench-state.types";
