export type FileNode = {
  name: string;
  kind: "folder" | "file";
  depth: number;
  open?: boolean;
  status?: "modified" | "new";
};

export const fileTree: FileNode[] = [
  { name: "codepilot-ai", kind: "folder", depth: 0, open: true },
  { name: "app", kind: "folder", depth: 1, open: true },
  { name: "api", kind: "folder", depth: 2 },
  { name: "globals.css", kind: "file", depth: 2 },
  { name: "layout.tsx", kind: "file", depth: 2 },
  { name: "page.tsx", kind: "file", depth: 2, status: "modified" },
  { name: "components", kind: "folder", depth: 1, open: true },
  { name: "ai", kind: "folder", depth: 2 },
  { name: "editor", kind: "folder", depth: 2, open: true },
  { name: "editor-shell.tsx", kind: "file", depth: 3, status: "new" },
  { name: "file-tabs.tsx", kind: "file", depth: 3 },
  { name: "lib", kind: "folder", depth: 1 },
  { name: "package.json", kind: "file", depth: 1 },
  { name: "README.md", kind: "file", depth: 1 },
];

export const codeLines = [
  ["keyword", "import"],
  ["plain", " { useMemo } "],
  ["keyword", "from"],
  ["string", ' "react"'],
  ["plain", ";"],
  ["break", ""],
  ["keyword", "import"],
  ["plain", " { EditorPanel } "],
  ["keyword", "from"],
  ["string", ' "./editor-panel"'],
  ["plain", ";"],
  ["break", ""],
  ["break", ""],
  ["keyword", "type"],
  ["type", " EditorShellProps"],
  ["plain", " = {"],
  ["break", ""],
  ["plain", "  projectId: "],
  ["type", "string"],
  ["plain", ";"],
  ["break", ""],
  ["plain", "  initialFile?: "],
  ["type", "string"],
  ["plain", ";"],
  ["break", ""],
  ["plain", "};"],
  ["break", ""],
  ["break", ""],
  ["keyword", "export function"],
  ["function", " EditorShell"],
  ["plain", "({ projectId, initialFile }: "],
  ["type", "EditorShellProps"],
  ["plain", ") {"],
  ["break", ""],
  ["plain", "  "],
  ["keyword", "const"],
  ["plain", " workspace = "],
  ["function", "useWorkspace"],
  ["plain", "(projectId);"],
  ["break", ""],
  ["plain", "  "],
  ["keyword", "const"],
  ["plain", " activeFile = "],
  ["function", "useMemo"],
  ["plain", "(() => {"],
  ["break", ""],
  ["plain", "    "],
  ["keyword", "return"],
  ["plain", " workspace.files.find((file) =>"],
  ["break", ""],
  ["plain", "      file.path === initialFile"],
  ["break", ""],
  ["plain", "    );"],
  ["break", ""],
  ["plain", "  }, [workspace.files, initialFile]);"],
  ["break", ""],
  ["break", ""],
  ["plain", "  "],
  ["keyword", "return"],
  ["plain", " ("],
  ["break", ""],
  ["plain", "    <"],
  ["type", "EditorPanel"],
  ["break", ""],
  ["plain", "      file={activeFile}"],
  ["break", ""],
  ["plain", "      onSave={workspace.saveFile}"],
  ["break", ""],
  ["plain", "    />"],
  ["break", ""],
  ["plain", "  );"],
  ["break", ""],
  ["plain", "}"],
] as const;

export const assistantSteps = [
  { label: "Inspect editor module", detail: "7 files reviewed", done: true },
  { label: "Map state boundaries", detail: "Zustand + server state", done: true },
  { label: "Implement editor shell", detail: "2 files changed", active: true },
  { label: "Run typecheck", detail: "Waiting", done: false },
];
